server:
  port: 8081
#应用名称定义，同时也是在eureka注册中心展示的名称
spring:
  application:
    name: rms-index
#商品客户端注册到eureka注册中心的服务器地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/,http://localhost:9081/eureka/
#商品服务在注册中心的名称，注意大写，名称定义在商品工程的yml中spring application name
RMS-PRODUCT:
  ribbon:
    #均衡策略 三种
    #轮训 RoundRobinRule
    #随机 RandomRule
    #最佳策略  过滤挂的服务器，并且返回请求数少的实例 BestAvailableRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
    #restTemplate开启对所有操作进行重试连接
    #OkToRetryOnAllOperations: true
    #切换实例目标，重试的次数
    #MaxAutoRetriesNextServer: 2
#让feign调用微服务支持熔断
#隔离 本来全心全意花全部精力去调这个服务的，现在开启线程池，只划分部分线程去调这个服务
#熔断  超过设置的时间就直接返回默认的fallback方案，进行提示或者返回默认操作或信息等
#hystrix默认超时1秒，这也是最佳方案设置
feign:
  hystrix:
    enabled: true