server:
  port: 8081
#应用名称定义，同时也是在eureka注册中心展示的名称
spring:
  application:
    name: rms-index
#商品客户端注册到eureka注册中心的服务器地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/
#商品服务在注册中心的名称，注意大写，名称定义在商品工程的yml中spring application name
RMS-PRODUCT:
  ribbon:
    #均衡策略 三种
    #轮训 RoundRobinRule
    #随机 RandomRule
    #最佳策略  过滤挂的服务器，并且返回请求数少的实例 BestAvailableRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
