server:
  port: 9080
instance:
    hostname: localhost
eureka:
  client:
    #不从eureka server获取注册信息
    fetch-registry: false
    #不将该服务注册到eureka server，因为这里代表的eureka本身
    #如果不配置false默认会去注册，但不能自己注册自己
    register-with-eureka: false
    #客户端与eureka服务端交互的地址
    service-url:
      defaultZone: http://${instance.hostname}:${server.port}/eureka
  #注意，线上必须开启自我保护，去掉下面的配置即可。
  server:
    #是否开启注册中心自我保护机制，开发的时候关闭
    #自我保护机制- 服务注册后，每隔30S会发次心跳，告诉注册中心服务健康，如果超过90s还没发将被服务删除
    #注册中心也会检测是否自己网络坏了，如果15分钟失败率超过85%将不会自我保护
    #注册中心很长的红色字就是自我保护的提示
    enable-self-preservation: false
    #删除服务间隔3秒（3s连不上删除注册服务）
    eviction-interval-timer-in-ms: 3000
