#应用名称定义，同时也是在eureka注册中心展示的名称
spring:
  application:
    name: rms-product
---
spring:
  profiles: productClinet1
server:
  port: 8080
#商品客户端注册到eureka注册中心的服务器地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/
---
spring:
  profiles: productClinet2
server:
  port: 8082
#商品客户端注册到eureka注册中心的服务器地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/